#!/usr/bin/python3
#SPDX-FileCopyrightText: 2022 Haruki Matsukawa 
#SPDX-License-Identifier: BSD-3-Clause
import sys
 
 
def tonum(s):   
  try:                  #失敗しそうな処理
      return int(s)     #文字列を整数に変換
  except:               #例外処理
      return float(s)   
 
 
ans = 0
for line in sys.stdin:      #標準入力から読んで出力
    line = line.rstrip()    #文字列の右側のスペースを削除
    ans += tonum(line)      

print(ans)